name: Build Docs Generator

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Build generator
        shell: pwsh
        run: dotnet build .\QaaS.Docs.Generator.csproj -c Release
